### ISSUE TITLE
In grafana some panel shows grafana-piechart-panel could not be found

### ISSUE THREAD

**Issue by ldd91** [DDNStorage/LustrePerfMon#14]
My lustre version is 2.12.2 and in the grafana UI,some panel shows Panel plugin with id grafana-piechart-panel could not be found,howerver when i install in lustre version 2.12.0 this problem did not  happen

**Comment by LiXi-storage** [comment]
Is it possible for you to take a screen shot and upload it here? It would be very helpful for debugging.

**Comment by ldd91** [comment]
![grafana-error](https://user-images.githubusercontent.com/29392150/61857769-55bb3c80-aef7-11e9-8209-141eedc2daa1.jpg)

**Comment by LiXi-storage** [comment]
Hi, I don't think this is caused by the Lustre version change. The plugin piechart-panel of Grafana is not installed some how. I would suggest to:

1. Check whether the plugins are copied to the proper directory properly:
`# ls /var/lib/grafana/plugins/`
Grafana_Status_panel  piechart-panel  savantly-heatmap-panel

2. If the plugin directorie are not complete, please manually fix it by coping the plugin directory into /var/lib/grafana/plugins. The plugins can be found in the ISO. 

3. If the ISO is broken, please rebuild the ISO or download the plugin from https://github.com/grafana/piechart-panel.

4. If the plugin are properly installed in /var/lib/grafana/plugins/, I guess need to restart Grafana to start using it:
`# service grafana-server restart`

**Comment by ldd91** [comment]
I exec ls /var/lib/grafana/plugins/ and it shows Grafana_Status_panel piechart-panel savantly-heatmap-panel,all plugins are here,and i run service grafana-server restart,however the grafana didnt change

**Comment by ldd91** [comment]
Thank you @LiXi-storage  I reinstalled piechart-panel and the problem solved
